/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sisdeportes;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author XCARET
 */
public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfondo = new javax.swing.JDesktopPane();
        jButton11 = new javax.swing.JButton();
        btncoleg = new javax.swing.JButton();
        btnlistalumnod2 = new javax.swing.JButton();
        btnDepor = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnNiveles = new javax.swing.JButton();
        btnUsuar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Deportes");

        jButton11.setText("Horarios Inscritos");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        pfondo.add(jButton11);
        jButton11.setBounds(70, 350, 160, 30);

        btncoleg.setText("Colegiaturas");
        btncoleg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolegActionPerformed(evt);
            }
        });
        pfondo.add(btncoleg);
        btncoleg.setBounds(70, 100, 160, 30);

        btnlistalumnod2.setText("Lista de Alumnos");
        btnlistalumnod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistalumnod2ActionPerformed(evt);
            }
        });
        pfondo.add(btnlistalumnod2);
        btnlistalumnod2.setBounds(70, 50, 160, 30);

        btnDepor.setText("Deportes");
        btnDepor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeporActionPerformed(evt);
            }
        });
        pfondo.add(btnDepor);
        btnDepor.setBounds(70, 150, 160, 30);

        jButton12.setText("Empleados");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        pfondo.add(jButton12);
        jButton12.setBounds(70, 200, 160, 30);

        btnNiveles.setText("Niveles");
        btnNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelesActionPerformed(evt);
            }
        });
        pfondo.add(btnNiveles);
        btnNiveles.setBounds(70, 250, 160, 30);

        btnUsuar.setText("Usuarios");
        btnUsuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarActionPerformed(evt);
            }
        });
        pfondo.add(btnUsuar);
        btnUsuar.setBounds(70, 300, 160, 30);

        jMenu1.setText("Registros");

        jMenuItem1.setText("Alumnos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Conceptos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Cursos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("Colaboradores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Niveles");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem8.setText("Usuarios");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Horarios");

        jMenuItem6.setText("Asignacion de cursos y docentes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Matriculas");

        jMenuItem7.setText("Lista de Matriculas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Pagos");

        jMenuItem9.setText("Pago de cuotas de matriculas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Consultas");

        jMenuItem10.setText("Consulta de pagos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ayuda");

        jMenuItem11.setText("Acerca de");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pfondo, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pfondo, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void Centrar(JDesktopPane fondo, JInternalFrame from)
    {
        Dimension tamaño_fondo = fondo.getSize();
        Dimension tamaño_vi = from.getSize();
        from.setLocation((tamaño_fondo.width - tamaño_vi.width)/2,(tamaño_fondo.height- tamaño_fondo.height)/2+30);
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FIListaAlumnos f= new FIListaAlumnos();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FIListaConceptos f= new FIListaConceptos();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FICursos f= new FICursos();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FIListaEmpleados f= new FIListaEmpleados();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FIListaNiveles f= new FIListaNiveles();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FIHorario f= new FIHorario();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FIListaMatriculas f= new FIListaMatriculas();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FIListaUsuarios f= new FIListaUsuarios();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FIPago f= new FIPago();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FIConsultaPagos f= new FIConsultaPagos();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FIAcerca f= new FIAcerca();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
  JTable jfrm2= new JTable();
        jfrm2.setSize(600, 6000); 
        jfrm2.setVisible(true);
       // this.setVisible(true);
       setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       //this.dispose();
  
       
 
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btncolegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolegActionPerformed
    FIListaConceptos f= new FIListaConceptos();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        
        f.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btncolegActionPerformed

    private void btnlistalumnod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistalumnod2ActionPerformed
      FIListaAlumnos f= new FIListaAlumnos();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        
        f.setVisible(true); // TODO add your handling code here:   // TODO add your handling code here:
    }//GEN-LAST:event_btnlistalumnod2ActionPerformed

    private void btnDeporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeporActionPerformed
 FICursos f= new FICursos();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        
        f.setVisible(true); 
    }//GEN-LAST:event_btnDeporActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        FIEmpleado f= new FIEmpleado();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        
        f.setVisible(true); 
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelesActionPerformed
 FIListaNiveles f= new FIListaNiveles();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        
        f.setVisible(true);     }//GEN-LAST:event_btnNivelesActionPerformed

    private void btnUsuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarActionPerformed
      FIListaUsuarios f= new FIListaUsuarios();
        pfondo.add(f);
        Centrar(pfondo, f);
        f.toFront();
        
        f.setVisible(true);    
    }//GEN-LAST:event_btnUsuarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepor;
    private javax.swing.JButton btnNiveles;
    private javax.swing.JButton btnUsuar;
    private javax.swing.JButton btncoleg;
    private javax.swing.JButton btnlistalumnod2;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JDesktopPane pfondo;
    // End of variables declaration//GEN-END:variables

    private void Centrar(JDesktopPane pfondo, JTable f) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
